// Code generated by protoc-gen-go. DO NOT EDIT.
// source: schnorrkey.proto

/*
Package Schnorrkey is a generated protocol buffer package.

It is generated from these files:
	schnorrkey.proto

It has these top-level messages:
	Priv
	Pub
*/
package Schnorrkey

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Priv struct {
	X                []byte `protobuf:"bytes,1,req,name=X,json=x" json:"X,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Priv) Reset()                    { *m = Priv{} }
func (m *Priv) String() string            { return proto.CompactTextString(m) }
func (*Priv) ProtoMessage()               {}
func (*Priv) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Priv) GetX() []byte {
	if m != nil {
		return m.X
	}
	return nil
}

type Pub struct {
	Y                []byte `protobuf:"bytes,1,req,name=Y,json=y" json:"Y,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Pub) Reset()                    { *m = Pub{} }
func (m *Pub) String() string            { return proto.CompactTextString(m) }
func (*Pub) ProtoMessage()               {}
func (*Pub) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Pub) GetY() []byte {
	if m != nil {
		return m.Y
	}
	return nil
}

func init() {
	proto.RegisterType((*Priv)(nil), "Schnorrkey.Priv")
	proto.RegisterType((*Pub)(nil), "Schnorrkey.Pub")
}

func init() { proto.RegisterFile("schnorrkey.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 82 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x12, 0x28, 0x4e, 0xce, 0xc8,
	0xcb, 0x2f, 0x2a, 0xca, 0x4e, 0xad, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x0a, 0x86,
	0x8b, 0x28, 0x89, 0x70, 0xb1, 0x04, 0x14, 0x65, 0x96, 0x09, 0xf1, 0x70, 0x31, 0x46, 0x48, 0x30,
	0x2a, 0x30, 0x69, 0xf0, 0x04, 0x31, 0x56, 0x28, 0x09, 0x73, 0x31, 0x07, 0x94, 0x26, 0x81, 0x04,
	0x23, 0x61, 0x82, 0x95, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x34, 0x4c, 0xef, 0x3b, 0x49, 0x00,
	0x00, 0x00,
}
