// Code generated by protoc-gen-go.
// source: tsmsg.proto
// DO NOT EDIT!

/*
Package TSmsg is a generated protocol buffer package.

It is generated from these files:
	tsmsg.proto

It has these top-level messages:
	Config
	Signal
*/
package TSmsg

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Config struct {
	SNo              *int32   `protobuf:"varint,1,req,name=SNo" json:"SNo,omitempty"`
	Epoch            *int32   `protobuf:"varint,2,req,name=Epoch" json:"Epoch,omitempty"`
	Epsilon          *float32 `protobuf:"fixed32,3,req,name=Epsilon" json:"Epsilon,omitempty"`
	Delta            *float32 `protobuf:"fixed32,4,req,name=Delta" json:"Delta,omitempty"`
	Ncps             *int32   `protobuf:"varint,5,req,name=Ncps" json:"Ncps,omitempty"`
	CPhname          []string `protobuf:"bytes,6,rep,name=CPhname" json:"CPhname,omitempty"`
	CPips            []string `protobuf:"bytes,7,rep,name=CPips" json:"CPips,omitempty"`
	Ndps             *int32   `protobuf:"varint,8,req,name=Ndps" json:"Ndps,omitempty"`
	DPhname          []string `protobuf:"bytes,9,rep,name=DPhname" json:"DPhname,omitempty"`
	DPips            []string `protobuf:"bytes,10,rep,name=DPips" json:"DPips,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *Config) Reset()                    { *m = Config{} }
func (m *Config) String() string            { return proto.CompactTextString(m) }
func (*Config) ProtoMessage()               {}
func (*Config) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Config) GetSNo() int32 {
	if m != nil && m.SNo != nil {
		return *m.SNo
	}
	return 0
}

func (m *Config) GetEpoch() int32 {
	if m != nil && m.Epoch != nil {
		return *m.Epoch
	}
	return 0
}

func (m *Config) GetEpsilon() float32 {
	if m != nil && m.Epsilon != nil {
		return *m.Epsilon
	}
	return 0
}

func (m *Config) GetDelta() float32 {
	if m != nil && m.Delta != nil {
		return *m.Delta
	}
	return 0
}

func (m *Config) GetNcps() int32 {
	if m != nil && m.Ncps != nil {
		return *m.Ncps
	}
	return 0
}

func (m *Config) GetCPhname() []string {
	if m != nil {
		return m.CPhname
	}
	return nil
}

func (m *Config) GetCPips() []string {
	if m != nil {
		return m.CPips
	}
	return nil
}

func (m *Config) GetNdps() int32 {
	if m != nil && m.Ndps != nil {
		return *m.Ndps
	}
	return 0
}

func (m *Config) GetDPhname() []string {
	if m != nil {
		return m.DPhname
	}
	return nil
}

func (m *Config) GetDPips() []string {
	if m != nil {
		return m.DPips
	}
	return nil
}

type Signal struct {
	SNo              *int32 `protobuf:"varint,1,req,name=SNo" json:"SNo,omitempty"`
	Fflag            *bool  `protobuf:"varint,2,req,name=Fflag" json:"Fflag,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Signal) Reset()                    { *m = Signal{} }
func (m *Signal) String() string            { return proto.CompactTextString(m) }
func (*Signal) ProtoMessage()               {}
func (*Signal) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Signal) GetSNo() int32 {
	if m != nil && m.SNo != nil {
		return *m.SNo
	}
	return 0
}

func (m *Signal) GetFflag() bool {
	if m != nil && m.Fflag != nil {
		return *m.Fflag
	}
	return false
}

func init() {
	proto.RegisterType((*Config)(nil), "TSmsg.Config")
	proto.RegisterType((*Signal)(nil), "TSmsg.Signal")
}

func init() { proto.RegisterFile("tsmsg.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 207 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0xcf, 0x31, 0x6e, 0xc3, 0x20,
	0x14, 0xc6, 0x71, 0x05, 0x07, 0x27, 0x79, 0x5d, 0x2a, 0xd4, 0xe1, 0x8d, 0x56, 0x26, 0x4f, 0x55,
	0xef, 0x60, 0xd2, 0x31, 0x8a, 0x70, 0x2f, 0x80, 0x62, 0x1b, 0x23, 0x61, 0x40, 0xc5, 0x87, 0xee,
	0x31, 0x2a, 0x1e, 0xb6, 0xba, 0x74, 0xe3, 0xff, 0x09, 0xfd, 0xa4, 0x07, 0x2f, 0x6b, 0x5a, 0x92,
	0x79, 0x8f, 0xdf, 0x61, 0x0d, 0x82, 0x7f, 0xf5, 0x4b, 0x32, 0xd7, 0x9f, 0x03, 0xd4, 0x5d, 0xf0,
	0x93, 0x35, 0xe2, 0x15, 0xaa, 0xfe, 0x1e, 0xf0, 0xd0, 0xb0, 0x96, 0xab, 0xfc, 0x14, 0x6f, 0xc0,
	0x6f, 0x31, 0x3c, 0x67, 0x64, 0xb4, 0x95, 0x10, 0x08, 0xa7, 0x5b, 0x4c, 0xd6, 0x05, 0x8f, 0x55,
	0xc3, 0x5a, 0xa6, 0xf6, 0xcc, 0xff, 0xe5, 0xe8, 0x56, 0x8d, 0x47, 0xda, 0x4b, 0x08, 0x01, 0xc7,
	0xfb, 0x33, 0x26, 0xe4, 0x84, 0xd0, 0x3b, 0x1b, 0xdd, 0x63, 0xf6, 0x7a, 0x19, 0xb1, 0x6e, 0xaa,
	0xf6, 0xa2, 0xf6, 0xcc, 0x46, 0xf7, 0xb0, 0x31, 0xe1, 0x89, 0xf6, 0x12, 0x64, 0x0c, 0x31, 0xe1,
	0x79, 0x33, 0x86, 0x62, 0xc8, 0xcd, 0xb8, 0x14, 0x43, 0xfe, 0x19, 0x92, 0x0c, 0x28, 0x06, 0xc5,
	0xf5, 0x03, 0xea, 0xde, 0x1a, 0xaf, 0xdd, 0xff, 0x97, 0x7e, 0x4e, 0x4e, 0x1b, 0xba, 0xf4, 0xac,
	0x4a, 0xfc, 0x06, 0x00, 0x00, 0xff, 0xff, 0xe7, 0x20, 0xbc, 0xae, 0x31, 0x01, 0x00, 0x00,
}
