// Code generated by protoc-gen-go.
// source: tsres.proto
// DO NOT EDIT!

/*
Package TSres is a generated protocol buffer package.

It is generated from these files:
	tsres.proto

It has these top-level messages:
	Response
*/
package TSres

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Response struct {
	SNo              *uint32 `protobuf:"varint,3,req,name=s_no,json=sNo" json:"s_no,omitempty"`
	CNo              *uint32 `protobuf:"varint,4,req,name=c_no,json=cNo" json:"c_no,omitempty"`
	F                *bool   `protobuf:"varint,5,req,name=f" json:"f,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Response) GetSNo() uint32 {
	if m != nil && m.SNo != nil {
		return *m.SNo
	}
	return 0
}

func (m *Response) GetCNo() uint32 {
	if m != nil && m.CNo != nil {
		return *m.CNo
	}
	return 0
}

func (m *Response) GetF() bool {
	if m != nil && m.F != nil {
		return *m.F
	}
	return false
}

func init() {
	proto.RegisterType((*Response)(nil), "TSres.Response")
}

func init() { proto.RegisterFile("tsres.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 100 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2e, 0x29, 0x2e, 0x4a,
	0x2d, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x0d, 0x09, 0x2e, 0x4a, 0x2d, 0x56, 0xb2,
	0xe3, 0xe2, 0x08, 0x4a, 0x2d, 0x2e, 0xc8, 0xcf, 0x2b, 0x4e, 0x15, 0x12, 0xe4, 0x62, 0x29, 0x8e,
	0xcf, 0xcb, 0x97, 0x60, 0x56, 0x60, 0xd2, 0xe0, 0x0d, 0x62, 0x2e, 0xf6, 0xcb, 0x07, 0x09, 0x25,
	0x83, 0x84, 0x58, 0x20, 0x42, 0xc9, 0x7e, 0xf9, 0x42, 0x3c, 0x5c, 0x8c, 0x69, 0x12, 0xac, 0x0a,
	0x4c, 0x1a, 0x1c, 0x41, 0x8c, 0x69, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x7f, 0x82, 0x16, 0xcd,
	0x54, 0x00, 0x00, 0x00,
}
